### PR TITLE
adds PHP latest plugin

### PR DESCRIPTION
**Pull request by artspb**

### CODE REVIEW

**Comment by WyriHaximus** [comment]
Have to admit I'm really in conflict about this one. First off it makes sure you have the latest PHP version available, on the other hand it messes with your system where IMHO an IDE has no place messing with.

**Comment by artspb** [comment]
It doesn't touch your system, actually. The interpreter is installed into the IDE cache. Everything's located inside a single directory so can be easily cleaned up if not needed.

**Comment by WyriHaximus** [comment]
Ah check it stores it somewhere in your PHPStorm config, great :+1: Thanks for the PR :tada:

**Comment by artspb** [comment]
Thank you!

**Pull request merged**
